# Generated by Django 4.0.2 on 2022-06-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='User',
            new_name='user',
        ),
    ]
